-- SORT THE CUSTOMERS FROM LOWEST TO HIGHEST SCORES WITH NULLS APPEARING LAST

SELECT 
CustomerID,
Score,
--COALESCE(Score,9999999999999),
CASE WHEN Score IS NULL THEN 1 ELSE 0 END FLAG
FROM Sales.Customers
ORDER BY  CASE WHEN Score IS NULL THEN 1 ELSE 0 END, Score