--NULLIF(VAL1,VAL2)

/*
COMPARES TWO EXPRESSION RETURNS
NULL IF THEY ARE EQUAL
FIRST VALUE IF THEY ARE NOT EQUAL
*/

   --FIND THE SALES PRICE FOR EACH ORDER BY DIVIDING THE SALES BY QUANTITY


   SELECT 
   OrderID,
   Sales,
   Quantity,
   Sales / NULLIF(Quantity,0) AS Price
   FROM Sales.Orders