SELECT
OrderID,
OrderDate,
OrderStatus,
Sales,
--SUM(Sales) OVER(PARTITION BY OrderStatus ORDER BY OrderDate
--ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING) TOTALSALES

SUM(Sales) OVER(PARTITION BY OrderStatus ORDER BY OrderDate
ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) TOTALSALES
FROM Sales.Orders