-- UNION : RETURNS ALL DISTRICT ROWS FROM BOTH QUERIES, REMOVES DUPLICATES FROM COMBINED SET

--- 1. COMBINE THE DATA FROM CUSTOMERS AND EMPLOYEES INTO ONE TABLE

SELECT 
	FirstName,
	LastName
FROM Sales.Customers

UNION

SELECT
	FirstName,
	LastName
FROM Sales.Employees