/* SELECT
ProductID,
OrderStatus,
SUM(Sales) OVER()
SUM(Sales) OVER(PARTITION BY ProductID)
SUM(Sales) OVER(PARTITION BY OrderStatus)
SUM(Sales) OVER(PARTITION BY ProductID,OrderStatus)
SUM(Sales) OVER(PARTITION BY ProductID ORDER BY OrderStatus)

FOR FRAME ORDER BY IS MUST
SUM(Sales) OVER(ORDER BY ProductID)
SUM(Sales) OVER(ORDER BY OrderStatus)
FROM Sales.Orders */



SELECT
ProductID,
OrderStatus,
Sales,

SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN CURRENT ROW AND CURRENT ROW),
SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING),
SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING),


SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN 2 PRECEDING AND CURRENT ROW),
SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN 2 PRECEDING AND 2 FOLLOWING),
SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN 2 PRECEDING AND UNBOUNDED FOLLOWING),

SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN UNBOUNDED  PRECEDING AND 2 FOLLOWING),
SUM(Sales) OVER(PARTITION BY  OrderStatus ORDER BY OrderStatus  ROWS BETWEEN UNBOUNDED  PRECEDING AND UNBOUNDED FOLLOWING)
FROM Sales.Orders