--CCORRELATED SUBQUERY IN WHERE CLAUSE EXISTS OPERATOR

/*
SELECT col1,col2,..
FROM tabl2
WHERE EXISTS (SELECT 1
	FROM TABLE1
	WHERE TABLE1.ID=TABLE2.ID
)
*/

--SHOW THE ORDERS DETAILS FOR CUSTOMERS IN GERMANY

SELECT 
*
FROM Sales.Orders o
WHERE EXISTS 
(
		SELECT 1
		FROM Sales.Customers c
		WHERE country = 'Germany'
		AND c.CustomerID=o.CustomerID )