-- CONVERT() : change a value to diff type

SELECT
CONVERT(INT,'123') AS [STRING TO INT CONVERT],
CONVERT(DATE,'2025-08-03') AS [STRING TO DATE CONVERT],
CONVERT(DATE,CreationTime) AS [DATETIME TO DATE CONVERT]
FROM Sales.Orders
--CONVERT(VARCHAR,OrderDate, '34')


SELECT
CreationTime,
CONVERT(DATE,CreationTime) AS [DATETIME TO DATE CONVERT],
CONVERT(VARCHAR, CreationTime, 32) AS USA_STYLE_32,
CONVERT(VARCHAR, CreationTime, 34) AS europer_STYLE_34
FROM Sales.Orders